// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//
//# HOPPERDUCTS
// ================================================================================
//#MARKER REMOVE

	recipes.remove(<BiblioCraft:item.BiblioGlasses:2>);
	recipes.remove(<BiblioCraft:item.FramingSaw>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
	recipes.addShapeless(<BiblioCraft:item.BiblioGlasses:2>, [<BiblioWoodsTFC:item.BiblioTFCItems:19>, <minecraft:glass_pane>]);
// ================================================================================
//#MARKER ADD SHAPED
