if (FML.isModLoaded("terrafirmacraft")) {
//Collapsing multi meta items to two examples only.
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlueSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlueSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBrassLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBrassLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioRedSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioRedSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodBookcase", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodshelf", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodtable", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack1", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack2", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack3", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack4", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack5", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodcase", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWooddesk", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodlabel", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodMapFrame", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodFancySign", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaneler", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodFancyWorkbench", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT0", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT1", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT2", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT3", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT4", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodClock", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodSeat", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodpotshelf", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.BismuthBronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.BlackBronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Brass", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Bronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Copper", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Gold", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Lead", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Platinum", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.RoseGold", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Silver", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.SterlingSilver", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.WroughtIron", [0,1]);
    NEI.override("OpenBlocks:tank", [0]);
    NEI.override("minecraft:potion", [0]);
    NEI.override("WR-CBE|Logic:wirelessLogic", [0,1]);
//Removals
  NEI.hide("Forestry:leaves");
  NEI.hide("cuchaz.ships:blockAirRoof");
  NEI.hide("cuchaz.ships:blockAirWall");
  NEI.hide("cuchaz.cuchazinteractive:token")
  NEI.hide("cuchaz.cuchazinteractive:listOfSupporters");
  NEI.hide("cuchaz.cuchazinteractive:supporterPlaque");
  NEI.hide("cuchaz.cuchazinteractive:shipPlaque");
  NEI.hide("WR-CBE|Addons:triangulator");
  NEI.hide("WR-CBE|Addons:sniffer");
  NEI.hide("WR-CBE|Addons:empty_map");
  NEI.hide("WR-CBE|Addons:map");
  NEI.hide("WR-CBE|Addons:tracker");
  NEI.hide("WR-CBE|Addons:rep");
  NEI.hide("WR-CBE|Addons:psniffer");
  NEI.hide("WR-CBE|Core:blazeTransceiver");
  NEI.hide("WR-CBE|Core:blazeRecieverDish");
  NEI.hide("weather2:WeatherMachine");
  NEI.hide("weather2:WeatherDeflector");
  NEI.hide("Forestry:ffarm")
}