if (FML.isModLoaded("terrafirmacraft")) {
//Collapsing multi meta items to two examples only.
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBismuthBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlackSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlueSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBlueSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBrassLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBrassLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBronzeLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioBronzeLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioRedSteelLamp", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioRedSteelLantern", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodBookcase", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodshelf", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodtable", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack1", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack2", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack3", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack4", [0,1]);
    NEI.override("BiblioWoodsTFC:seatBack5", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodcase", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWooddesk", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodlabel", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodMapFrame", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodFancySign", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaneler", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodFancyWorkbench", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT0", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT1", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT2", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT3", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodPaintingT4", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodClock", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodSeat", [0,1]);
    NEI.override("BiblioWoodsTFC:BiblioWoodpotshelf", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.BismuthBronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.BlackBronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Brass", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Bronze", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Copper", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Gold", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Lead", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Platinum", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.RoseGold", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.Silver", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.SterlingSilver", [0,1]);
    NEI.override("DecorationsTFC:item.LanternCore.WroughtIron", [0,1]);
    NEI.override("OpenBlocks:tank", [0]);


//Removals
    NEI.hide("streams:*");
    NEI.hide("terrafirmacraft:FreshWater");
    NEI.hide("terrafirmacraft:FreshWaterStationary");
    NEI.hide("terrafirmacraft:HotWater");
    NEI.hide("terrafirmacraft:HotWaterStationary");
    NEI.hide("terrafirmacraft:Lava");
    NEI.hide("terrafirmacraft:LavaStationary");
    NEI.hide("terrafirmacraft:SaltWater");
    NEI.hide("terrafirmacraft:SaltWaterStationary");
    NEI.hide("minecraft:chainmail_boots");
    NEI.hide("minecraft:chainmail_chestplate");
    NEI.hide("minecraft:chainmail_helmet");
    NEI.hide("minecraft:chainmail_leggings");
    NEI.hide("minecraft:diamond");
    NEI.hide("minecraft:diamond_axe");
    NEI.hide("minecraft:diamond_block");
    NEI.hide("minecraft:diamond_boots");
    NEI.hide("minecraft:diamond_chestplate");
    NEI.hide("minecraft:diamond_helmet");
    NEI.hide("minecraft:diamond_hoe");
    NEI.hide("minecraft:diamond_leggings");
    NEI.hide("minecraft:diamond_ore");
    NEI.hide("minecraft:diamond_pickaxe");
    NEI.hide("minecraft:diamond_shovel");
    NEI.hide("minecraft:diamond_sword");
    NEI.hide("minecraft:dirt");
    NEI.hide("minecraft:emerald");
    NEI.hide("minecraft:emerald_ore");
    NEI.hide("minecraft:farmland");
    NEI.hide("minecraft:fence");
    NEI.hide("minecraft:fence_gate");
    NEI.hide("minecraft:fishing_rod");
    NEI.hide("minecraft:flowing_lava");
    NEI.hide("minecraft:flowing_water");
    NEI.hide("minecraft:golden_axe");
    NEI.hide("minecraft:golden_boots");
    NEI.hide("minecraft:golden_chestplate");
    NEI.hide("minecraft:golden_helmet");
    NEI.hide("minecraft:gold_ingot");
    NEI.hide("minecraft:golden_leggings");
    NEI.hide("minecraft:gold_ore");
    NEI.hide("minecraft:golden_pickaxe");
    NEI.hide("minecraft:golden_shovel");
    NEI.hide("minecraft:golden_sword");
    NEI.hide("minecraft:grass");
    NEI.hide("minecraft:gravel");
    NEI.hide("minecraft:iron_axe");
    NEI.hide("minecraft:iron_boots");
    NEI.hide("minecraft:iron_chestplate");
    NEI.hide("minecraft:iron_helmet");
    NEI.hide("minecraft:iron_hoe");
    NEI.hide("minecraft:iron_ingot");    
    NEI.hide("minecraft:iron_leggings");
    NEI.hide("minecraft:iron_ore");
    NEI.hide("minecraft:iron_pickaxe");
    NEI.hide("minecraft:iron_shovel");
    NEI.hide("minecraft:iron_sword");
    NEI.hide("minecraft:lapis_block");
    NEI.hide("minecraft:lapis_ore");
    NEI.hide("minecraft:lava");
    NEI.hide("minecraft:leather");
    NEI.hide("minecraft:leather_boots");
    NEI.hide("minecraft:leather_chestplate");
    NEI.hide("minecraft:leather_helmet");
    NEI.hide("minecraft:leather_leggings");
    NEI.hide("minecraft:wooden_axe");
    NEI.hide("minecraft:wooden_hoe");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("minecraft:wooden_shovel");
    NEI.hide("minecraft:wooden_sword");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("Mekanism:OreBlock");
    NEI.hide("Railcraft:ore");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("minecraft:wooden_pickaxe");
    NEI.hide("minecraft:wooden_pickaxe");    
    NEI.hide("Forestry:ingotBronze");
    NEI.hide("Forestry:ingotCopper");
    NEI.hide("Forestry:ingotTin");
    NEI.hide("Railcraft:ingot");
    NEI.hide("Tubestuff:machine:0");
    NEI.hide("Tubestuff:machine:1");
    NEI.hide("Tubestuff:machine:2");
    NEI.hide("Tubestuff:machine:4");
    NEI.hide("Tubestuff:machine:6");
    NEI.hide("Tubestuff:machine:8");
    NEI.hide("Tubestuff:uselessItem");


    
}