// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//
// RPG Adventure Mod
// ================================================================================
//#MARKER REMOVE

recipes.remove(<RPGAdvMod:glowcrumb>);
recipes.remove(<RPGAdvMod:signwall:1>);
recipes.remove(<RPGAdvMod:sign:6>);
recipes.remove(<RPGAdvMod:sign:5>);
recipes.remove(<RPGAdvMod:pole:1>);

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.addShapeless(<RPGAdvMod:glowcrumb> * 16, [<ore:blockGravel>, <ore:dustGlowstone>]);
// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

recipes.addShapeless(<RPGAdvMod:signwall:1>, [<RPGAdvMod:signwall>, <ore:bucketWater>]);

// ================================================================================
//#MARKER ADD SHAPED

	recipes.addShaped(<RPGAdvMod:sign:6> * 4, [[null, <terrafirmacraft:Flowers2:*>, null], [null, <minecraft:sign>, null], [null, <terrafirmacraft:Flowers:*>, null]]);
	recipes.addShaped(<RPGAdvMod:sign:6> * 4, [[null, <terrafirmacraft:Flowers:*>, null], [null, <minecraft:sign>, null], [null, <terrafirmacraft:Flowers2:*>, null]]);
	recipes.addShaped(<RPGAdvMod:sign:6> * 4, [[null, <terrafirmacraft:Flowers2:*>, null], [null, <minecraft:sign>, null], [null, <terrafirmacraft:Flowers2:*>, null]]);
	recipes.addShaped(<RPGAdvMod:sign:6> * 4, [[null, <terrafirmacraft:Flowers:*>, null], [null, <minecraft:sign>, null], [null, <terrafirmacraft:Flowers:*>, null]]);
	recipes.addShaped(<RPGAdvMod:sign:5> * 4, [[null, <ore:stoneRaw>, null], [null, <minecraft:sign>, null], [null, <ore:stoneRaw>, null]]);
	recipes.addShaped(<RPGAdvMod:pole:1> * 2, [[null, <ore:plankWood>, null], [<ore:stoneBricks>, <ore:plankWood>, <ore:stoneBricks>], [null, <ore:plankWood>, null]]);